export default {
    // private
    home:"/",
    dashboard: '/dashboard',
    propertycontent:'/property',
    newrenovationtab: '/newrenovationtab',
    financingone: '/financingone',
    purchase:'/purchase',
    income: '/income',
    fixedexpenses: '/fixedexpenses',
    variableexpenses: '/variableexpenses',
    assumptions: '/assumptions',
    report: '/report',
    expenses: '/expenses',
    fixedvariable: '/fixedvariable',

    // Slugs for Calculator two
    propertycontenttwo:'/propertytwo',
    purchasetwo:'/purchasetwo',
    renovation: '/renovation',
    financingtwo: '/financingtwo',
    incometwo: '/incometwo',
    fixedexpensestwo: '/fixedexpensestwo',
    variableexpensestwo: '/variableexpensestwo',
    expensetwo: '/expensetwo',
    reporttwo: '/reporttwo',
    // expensetwofixed: '/expensetwo/fixed',
    // expensetwovariable: '/expense/variable',
    assumptionstwo: '/assumptionstwo',
    reportdeskone: '/reportone',
    reportdesktwo: '/reportdesktwo',
    reportdeskthree: '/reportdeskthree',
    reportdeskfour: '/reportdeskfour',
    reportdeskfive: '/reportdeskfive',
    reportdesksix: '/reportdesksix',
    reportdeskseven: '/reportdeskseven',
    reportdeskeight: '/reportdeskeight',
    reportdesknine: '/reportdesknine',
    // overview: '/purchase',
    // overviewTwo: '/overview/two',
    // overviewThree: '/overview/three',
    // tickets: '/tickets',
    // ideas: '/ideas',
    // ideasTwo: '/ideas/two',
    // ideasThree: '/ideas/three',
    // contacts: '/contacts',
    // agents: '/agents',
    // articles: '/articles',
    // settings: '/settings',
    // subscription: '/subscription',
    // // auth
    // login: '/login',
    // signup: '/signup',
    // forgotPassword: '/forgot_password'   
};
